(() => {
  const q=id=>document.getElementById(id),SEARCH_AFTER_KM=.5,SEARCH_AFTER_MS=90000,RELAY_POLL_MS=2000,RELAY_STALE_MS=15000;
  const drive={watchId:null,relayTimer:null,elapsedTimer:null,startedAt:0,running:false,searchPosition:null,lastSearchAt:0,searchRunning:false,headingReady:false,lastAnnouncedId:null,relayTimestamp:null,fixedHeading:null,destination:null,vehicleHeading:null};
  const rad=v=>v*Math.PI/180,deg=v=>v*180/Math.PI;
  function kmBetween(a,b){const R=6371,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
  function bearingBetween(a,b){const p1=rad(a.lat),p2=rad(b.lat),dl=rad(b.lng-a.lng);return(deg(Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl)))+360)%360;}
  function fmtElapsed(ms){const s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),r=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`:`${m}:${String(r).padStart(2,'0')}`;}
  function updateElapsed(){if(q('drive-elapsed')&&drive.running)q('drive-elapsed').textContent=fmtElapsed(Date.now()-drive.startedAt);}
  function setIndicator(t,a=false){q('drive-indicator').textContent=t;q('drive-indicator').classList.toggle('active',a);} function setDriveStatus(t){q('drive-status').textContent=t;}
  function installDestinationUi(){const box=document.querySelector('.drive-box');if(!box||q('journey-destination'))return;const source=q('gps-source')?.closest('label');if(!source)return;const wrap=document.createElement('div');wrap.innerHTML=`<label>Destination<input id="journey-destination" type="text" placeholder="e.g. Brisbane or 123 Queen St, Brisbane" autocomplete="off"></label><div class="drive-readouts"><div><span>Fixed search heading</span><strong id="fixed-heading-value">—</strong></div></div><p class="hint">Used by both live Drive Mode and Replay. The heading is calculated once from the journey start to this destination and then remains fixed.</p>`;while(wrap.firstChild)box.insertBefore(wrap.firstChild,source);}
  function updateReadouts(p,c){const s=Number.isFinite(p.coords.speed)?p.coords.speed*3.6:null;q('drive-speed').textContent=s===null?'—':`${s.toFixed(1)} km/h`;q('drive-accuracy').textContent=Number.isFinite(p.coords.accuracy)?`±${Math.round(p.coords.accuracy)} m`:'—';const h=Number(p.coords.heading);if(Number.isFinite(h)&&h>=0)drive.vehicleHeading=h;q('drive-heading-value').textContent=drive.vehicleHeading===null?'—':`${Math.round(drive.vehicleHeading)}°`;q('drive-distance').textContent=drive.searchPosition?`${kmBetween(drive.searchPosition,c).toFixed(2)} km`:'—';updateElapsed();}
  function speakActivePoi(){if(!q('speak-pois').checked)return;const p=state.shortlist[state.activeIndex];if(!p||p.id===drive.lastAnnouncedId)return;drive.lastAnnouncedId=p.id;if(window.roadDiscoverExperience){roadDiscoverExperience.speak(roadDiscoverExperience.announcement(p));return;}if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`Coming up is ${p.name}.`);u.rate=.95;speechSynthesis.speak(u);}}
  async function runDriveSearch(c){if(!drive.running||drive.searchRunning||!drive.headingReady)return;drive.searchRunning=true;setIndicator('Searching',true);setDriveStatus(`Refreshing places of interest toward ${drive.destination?.name||'destination'} on fixed heading ${Math.round(drive.fixedHeading)}°…`);try{await searchGoogle();drive.searchPosition=c;drive.lastSearchAt=Date.now();q('drive-distance').textContent='0.00 km';speakActivePoi();const a=state.shortlist[state.activeIndex];setDriveStatus(a?`Tracking toward ${drive.destination.name}. Current active POI: ${a.name}.`:`Tracking toward ${drive.destination.name}. No eligible POI currently ahead.`);}catch(e){setDriveStatus(`Automatic POI search failed: ${e.message}`);}finally{drive.searchRunning=false;if(drive.running)setIndicator('Driving',true);}}
  function maybeSearch(c){if(!drive.headingReady)return;if(!drive.searchPosition){runDriveSearch(c);return;}const m=kmBetween(drive.searchPosition,c),e=Date.now()-drive.lastSearchAt;if(m>=SEARCH_AFTER_KM||e>=SEARCH_AFTER_MS)runDriveSearch(c);else setDriveStatus(`Tracking toward ${drive.destination.name} on fixed heading ${Math.round(drive.fixedHeading)}°. Next POI refresh after another ${Math.max(0,SEARCH_AFTER_KM-m).toFixed(2)} km or 90 seconds.`);}
  function onPosition(p){if(!drive.running)return;const c={lat:p.coords.latitude,lng:p.coords.longitude};q('latitude').value=c.lat.toFixed(6);q('longitude').value=c.lng.toFixed(6);updateReadouts(p,c);maybeSearch(c);}
  function onPositionError(e){setDriveStatus(({1:'Location permission was denied.',2:'Current location is unavailable.',3:'Location request timed out.'})[e.code]||`Location error: ${e.message||'unknown error'}`);}
  async function pollRelay(){if(!drive.running||q('gps-source').value!=='iphone')return;const s=q('gps-session').value.trim().toLowerCase();try{const r=await fetch(`api/gps.php?session=${encodeURIComponent(s)}&_=${Date.now()}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);if(Date.now()-Number(d.timestamp||0)>RELAY_STALE_MS){setDriveStatus('Waiting for a fresh iPhone GPS update.');setIndicator('Waiting for iPhone',true);return;}if(drive.relayTimestamp===d.timestamp)return;drive.relayTimestamp=d.timestamp;onPosition({coords:{latitude:Number(d.latitude),longitude:Number(d.longitude),accuracy:d.accuracy===null?null:Number(d.accuracy),speed:d.speed===null?null:Number(d.speed),heading:d.heading===null?null:Number(d.heading)},timestamp:Number(d.timestamp)});setIndicator('iPhone GPS live',true);}catch(e){setIndicator('Waiting for iPhone',true);setDriveStatus(`Waiting for iPhone GPS: ${e.message}`);}}
  async function resolveDestination(name){const r=await fetch('api/destination.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({destination:name})}),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return{name:d.name,address:d.address,lat:Number(d.latitude),lng:Number(d.longitude)};}
  async function getStartPosition(source){if(source==='iphone'){const s=q('gps-session').value.trim().toLowerCase(),r=await fetch(`api/gps.php?session=${encodeURIComponent(s)}&_=${Date.now()}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error('Start GPS Relay first so RDL has a current starting position.');if(Date.now()-Number(d.timestamp||0)>RELAY_STALE_MS)throw new Error('GPS Relay position is stale. Start the journey on the iPhone first.');return{lat:Number(d.latitude),lng:Number(d.longitude)};}return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),reject,{enableHighAccuracy:true,timeout:20000,maximumAge:2000}));}
  async function setFixedHeading(start){const destinationName=q('journey-destination')?.value.trim();if(!destinationName)throw new Error('Enter a destination before starting the journey.');const destination=await resolveDestination(destinationName),fixedHeading=bearingBetween(start,destination);q('heading').value=Math.round(fixedHeading);q('heading').readOnly=true;if(q('fixed-heading-value'))q('fixed-heading-value').textContent=`${Math.round(fixedHeading)}°`;return{destination,fixedHeading};}
  async function startDrive(){if(drive.running)return;if(!window.isSecureContext){setDriveStatus('Drive Mode requires HTTPS (or localhost).');return;}const source=q('gps-source').value;if(source==='laptop'&&!navigator.geolocation){setDriveStatus('This browser does not support geolocation.');return;}const session=q('gps-session').value.trim().toLowerCase();if(source==='iphone'&&!/^[a-z0-9_-]{3,32}$/.test(session)){setDriveStatus('GPS session code must be 3–32 letters, numbers, dashes or underscores.');return;}q('start-drive').disabled=true;setIndicator('Preparing',true);setDriveStatus('Resolving destination and calculating fixed journey heading…');try{const start=await getStartPosition(source),fixed=await setFixedHeading(start);Object.assign(drive,{running:true,searchPosition:null,lastSearchAt:0,headingReady:true,lastAnnouncedId:null,relayTimestamp:null,startedAt:Date.now(),fixedHeading:fixed.fixedHeading,destination:fixed.destination,vehicleHeading:null});q('latitude').value=start.lat.toFixed(6);q('longitude').value=start.lng.toFixed(6);q('stop-drive').disabled=false;q('gps-source').disabled=true;q('gps-session').disabled=true;q('journey-destination').disabled=true;if(q('drive-elapsed'))q('drive-elapsed').textContent='0:00';drive.elapsedTimer=setInterval(updateElapsed,1000);setDriveStatus(`Destination: ${fixed.destination.name}. Fixed journey/search heading: ${Math.round(fixed.fixedHeading)}°. This heading will not change during the journey.`);if(source==='iphone'){setIndicator('Waiting for iPhone',true);pollRelay();drive.relayTimer=setInterval(pollRelay,RELAY_POLL_MS);return;}setIndicator('Starting',true);drive.watchId=navigator.geolocation.watchPosition(onPosition,onPositionError,{enableHighAccuracy:true,timeout:20000,maximumAge:2000});}catch(e){q('start-drive').disabled=false;setIndicator('Stopped');setDriveStatus(`Could not start journey: ${e.message}`);}}
  function stopDrive(){if(drive.watchId!==null)navigator.geolocation.clearWatch(drive.watchId);if(drive.relayTimer!==null)clearInterval(drive.relayTimer);if(drive.elapsedTimer!==null)clearInterval(drive.elapsedTimer);Object.assign(drive,{watchId:null,relayTimer:null,elapsedTimer:null,running:false,searchRunning:false});q('start-drive').disabled=false;q('stop-drive').disabled=true;q('gps-source').disabled=false;q('gps-session').disabled=false;q('journey-destination').disabled=false;q('heading').readOnly=false;setIndicator('Stopped');setDriveStatus(drive.destination?`Drive Mode stopped. Destination was ${drive.destination.name}; fixed search heading was ${Math.round(drive.fixedHeading)}°.`:'Drive Mode stopped.');if('speechSynthesis'in window)speechSynthesis.cancel();}
  function updateSourceUi(){q('gps-session-row').hidden=q('gps-source').value!=='iphone';}
  installDestinationUi();window.rdlJourney={resolveDestination,bearingBetween,setFixedHeading};q('start-drive').addEventListener('click',startDrive);q('stop-drive').addEventListener('click',stopDrive);q('gps-source').addEventListener('change',updateSourceUi);addEventListener('beforeunload',stopDrive);updateSourceUi();
})();