<?php
$version = 'RDL Prototype 4 — Discovery & Tell Me More';
$cssVersion = filemtime(__DIR__ . '/styles.css');
$jsVersion = filemtime(__DIR__ . '/app.js');
$driveVersion = file_exists(__DIR__ . '/drive.js') ? filemtime(__DIR__ . '/drive.js') : time();
$experienceVersion = file_exists(__DIR__ . '/experience.js') ? filemtime(__DIR__ . '/experience.js') : time();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>RoadDiscover Laboratory</title><link rel="stylesheet" href="styles.css?v=<?= $cssVersion ?>"></head><body>
<header class="topbar"><div><p class="eyebrow">RoadDiscover</p><h1>POI Selection Laboratory</h1></div><span class="version"><?= htmlspecialchars($version) ?></span></header>
<main class="layout"><aside class="panel controls"><h2>Journey</h2><div class="grid two"><label>Latitude<input id="latitude" type="number" step="0.000001" value="-26.3911"></label><label>Longitude<input id="longitude" type="number" step="0.000001" value="153.0317"></label><label>Heading °<input id="heading" type="number" min="0" max="359" value="90"></label><label>Search ahead km<input id="radius" type="number" min="1" max="50" value="15"></label></div><p class="hint">Google searches a circle centred halfway ahead.</p><button id="use-location" class="secondary" type="button">Use my current location</button>
<section class="drive-box"><div class="drive-title-row"><div><p class="eyebrow">Road test</p><h2>Drive Mode</h2></div><span id="drive-indicator" class="drive-indicator">Stopped</span></div><label>GPS source<select id="gps-source"><option value="iphone" selected>iPhone GPS relay</option><option value="laptop">This laptop</option></select></label><label id="gps-session-row">GPS session code<input id="gps-session" value="roadtest" maxlength="32" autocomplete="off"></label><p class="hint">On the iPhone open <strong>/rdl/gps/</strong>, use the same session code, then tap Start GPS.</p><div class="drive-actions"><button id="start-drive" type="button">Start Drive</button><button id="stop-drive" class="danger" type="button" disabled>Stop</button></div><label class="drive-option"><input id="speak-pois" type="checkbox" checked><span>Speak new active POIs</span></label><div class="drive-readouts"><div><span>Speed</span><strong id="drive-speed">—</strong></div><div><span>GPS accuracy</span><strong id="drive-accuracy">—</strong></div><div><span>Travel heading</span><strong id="drive-heading-value">—</strong></div><div><span>Since search</span><strong id="drive-distance">—</strong></div></div><p id="drive-status" class="drive-status">Ready for a road test.</p></section>
<h2>Interests</h2><p class="hint">High interests rank ahead of Normal. Within each level, forward distance ranks candidates.</p><button id="all-interests-off" class="secondary" type="button">Turn all interests Off</button><div id="interests" class="interest-list"><?php $interestRows=[['history','History & heritage','normal'],['churches','Churches & religious sites','normal'],['nature','Nature & scenery','normal'],['gardens','Gardens','normal'],['architecture','Architecture','normal'],['museums','Museums & galleries','normal'],['coast','Beaches & coast','normal'],['wildlife','Wildlife','normal'],['engineering','Engineering & infrastructure','normal'],['accommodation','Hotels & accommodation','off'],['retail','Shops & retail','off'],['food','Restaurants & cafes','off'],['business','Businesses & services','off']];foreach($interestRows as[$key,$label,$defaultLevel]):?><label class="interest-row"><span><?=htmlspecialchars($label)?></span><select data-interest="<?=htmlspecialchars($key)?>"><option value="off"<?=$defaultLevel==='off'?' selected':''?>>Off</option><option value="normal"<?=$defaultLevel==='normal'?' selected':''?>>Normal</option><option value="high"<?=$defaultLevel==='high'?' selected':''?>>High</option></select></label><?php endforeach;?></div><div class="actions"><button id="search" type="button">Find POIs ahead</button><button id="demo" class="secondary" type="button">Load demo candidates</button></div><p id="status" class="status">Ready.</p></aside>
<section class="workspace"><article id="discovery-card" class="discovery-card empty"><p class="eyebrow">Level 1 — Discovery</p><h2 id="discovery-name">Waiting for a discovery</h2><p id="discovery-announcement" class="discovery-announcement">When RoadDiscover selects a POI, its driver announcement will appear here.</p><div class="discovery-actions"><button id="tell-more" type="button" disabled>Tell Me More</button><button id="speak-discovery" class="secondary" type="button" disabled>Speak Again</button><button id="discovery-next" class="danger" type="button" disabled>Not Interested / Next</button></div></article>
<article id="tell-more-card" class="tell-more-card" hidden><div><p class="eyebrow">Level 2 — Tell Me More</p><h2 id="tell-more-name">More information</h2></div><p id="tell-more-text" class="tell-more-text"></p><div id="tell-more-facts" class="tell-more-facts"></div><div class="discovery-actions"><button id="speak-more" type="button">Speak This</button><button id="close-more" class="secondary" type="button">Back to Discovery</button><button id="conversation-placeholder" class="secondary" type="button" disabled>Conversation — Level 3 later</button></div><p id="tell-more-status" class="status"></p></article>
<div class="summary-row"><article class="stat"><strong id="candidate-count">0</strong><span>Candidates</span></article><article class="stat"><strong id="eligible-count">0</strong><span>Eligible</span></article><article class="stat"><strong id="shortlist-count">0</strong><span>Shortlisted</span></article><article class="stat"><strong id="active-distance">—</strong><span>Next POI</span></article></div><article id="active-card" class="active-card empty"><div><p class="eyebrow">Selection engine</p><h2 id="active-name">No POI selected</h2><p id="active-meta">Run a search to create a shortlist.</p><p id="active-reason" class="reason"></p></div><div class="active-actions"><button id="accept" type="button" disabled>Accept</button><button id="reject" class="danger" type="button" disabled>Reject / next</button></div></article>
<article class="research-panel"><div class="research-heading"><div><p class="eyebrow">Research mode</p><h2>Google types returned</h2></div><button id="clear-type-filter" class="secondary small" type="button" hidden>Show all candidates</button></div><div id="type-summary" class="type-summary"><span class="empty-note">Run a search to inspect Google's returned types.</span></div></article><div class="table-wrap"><table class="research-table"><thead><tr><th>Rank</th><th>Place</th><th>Primary Google type</th><th>All Google types</th><th>RD interest</th><th>Prominence</th><th>Distance</th><th>Direction</th><th>Decision</th><th>Info</th></tr></thead><tbody id="results"><tr><td colspan="10" class="empty-cell">No candidates yet.</td></tr></tbody></table></div></section></main>
<div id="details-modal" class="modal" hidden><div class="modal-backdrop" data-close-details></div><section class="modal-card"><button class="modal-close" type="button" data-close-details>×</button><p class="eyebrow">Google Places details</p><h2 id="details-name">Place details</h2><p id="details-type" class="details-type"></p><p id="details-summary" class="details-summary"></p><div id="details-grid" class="details-grid"></div><div id="details-hours" class="details-hours"></div><div id="details-links" class="details-links"></div><p id="details-status" class="status"></p></section></div>
<script>window.addEventListener('error',function(event){var status=document.getElementById('status');if(status)status.textContent='JavaScript error: '+(event.message||'unknown error')+(event.lineno?' (line '+event.lineno+')':'');});</script><script src="app.js?v=<?=$jsVersion?>"></script><script src="experience.js?v=<?=$experienceVersion?>"></script><script src="drive.js?v=<?=$driveVersion?>"></script></body></html>